apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "600Gi"
        cpu: "1.5"
      requests:
        memory: "500Mi"
        cpu: "1"

