apiVersion: v1
kind: PersistentVolume
metadata:
  name: mylocalvol
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /vishal/volume1
